#     ____  _
#    / __ \(_)___ _____ ___  _______
#   / /_/ / / __ `/ __ `/ / / / ___/
#  / ____/ / /_/ / /_/ / /_/ (__  )
# /_/   /_/\__, /\__, /\__, /____/
#         /____//____//____/
#
# ${project.name} - v{project.version}
# Developed by https://codeitforyou.com/
#

settings:
  item: SKULL_ITEM
  min: 1
  max: 500000
  cooldown: 30 # seconds

# If specified as a SKULL_ITEM, you can specify its texture using:
# skull: "BASE-64-STRING"
# Uncomment the above and set your string.

drops:
  enabled: true
  chance: 50 # percent
  money:
    min: 1000
    max: 100000