name: ${plugin}
version: ${project.version}
main: ${package}
author: Chazza
website: https://plugins.gg
softdepend: ["PlaceholderAPI", "WorldGuard", "Vault"]

commands:
  piggybanks:
    description: PiggyBanks commands
    usage: ""
    aliases: ["pbanks", "piggy", "withdraw"]

permissions:
  piggybanks.reload:
    description: Reload the configuration file into memory
  piggybanks.withdraw:
    description: Ability to create a piggybank
    default: true