name: ${project.name}
version: ${project.version}
main: ${package}.${project.name}
author: CodeItForYou
website: ${website}
depend: ["Vault"]
api-version: "1.13"

commands:
  cifypiggys:
    description: CIFYPiggys commands
    usage: ""
    aliases: ["piggybanks", "pbanks", "piggy", "piggys"]
  withdraw:
    description: CIFYPiggys commands
    usage: ""
    aliases: ["deposit"]

permissions:
  cifypiggys.reload:
    description: Reload the configuration file into memory
  cifypiggys.withdraw:
    description: Ability to create a piggybank
    default: true