name: ${plugin}
version: ${project.version}
main: ${package}
author: CodeItForYou
website: ${website}
depend: ["Vault"]

permissions:
  cifypiggys.reload:
    description: Reload the configuration file into memory
  cifypiggys.withdraw:
    description: Ability to create a piggybank
    default: true